name: CI

on:
    push:
        paths:
            - "src/**.py"
            - pyproject.toml
            - poetry.lock
            - Dockerfile
            - .dockerignore

env:
    IMAGE_NAME: repo-watcher-dispatch-sender

jobs:
    build-image:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Get Revision
              run: |
                  revision=${GITHUB_REF##*/}-${GITHUB_SHA::7}-$(date +'%Y%m%d%H%M')
                  echo "revision=$revision" >> $GITHUB_ENV

            - name: Build image
              run: |
                  docker build \
                    --build-arg REVISION=$revision \
                    --tag ghcr.io/divideprojects/$IMAGE_NAME:latest \
                    --tag ghcr.io/divideprojects/$IMAGE_NAME:$revision \
                    .

            - name: Push image to GitHub Packages
              run: |
                  docker push ghcr.io/divideprojects/$IMAGE_NAME:$revision
                  docker push ghcr.io/divideprojects/$IMAGE_NAME:latest
