name: CI

on:
    push:
        paths:
            - "src/**.py"
            - pyproject.toml
            - poetry.lock
            - Dockerfile
            - .dockerignore

env:
    IMAGE_NAME: repo-watcher-dispatch-sender
    USER: divideprojects

jobs:
    build-image:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Get Revision
              run: |
                  revision=$(git rev-parse --short HEAD)
                  echo "revision=$revision" >> $GITHUB_ENV

            - name: Build image
              run: |
                  docker build \
                    --tag ghcr.io/$USER/$IMAGE_NAME:latest \
                    --tag ghcr.io/$USER/$IMAGE_NAME:$revision \
                    --tag docker.io/$USER/$IMAGE_NAME:latest \
                    --tag docker.io/$USER/$IMAGE_NAME:$revision \
                    .

            - name: Push image to GitHub Packages
              run: |
                  docker push ghcr.io/$USER/$IMAGE_NAME:$revision
                  docker push ghcr.io/$USER/$IMAGE_NAME:latest
                  docker push docker.io/$USER/$IMAGE_NAME:latest
                  docker push docker.io/$USER/$IMAGE_NAME:$revision
