name: Update Docker Hub Description

on:
    push:
        paths:
            - README.md
            - .github/workflows/update-docker-readme.yml

jobs:
    build-image:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Docker Hub Description
              uses: peter-evans/dockerhub-description@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
